### ISSUE TITLE
Ink Sack used as "unknown"

### ISSUE THREAD

**Issue by TheProducer835** [codingWithJimmy/LogToSplunk#7]
When you use the /give command I've noticed that certain items such as bonemeal are spoken of in the response as "Ink Sack". THat's the go-to for a few items.

The problem here is: I just harvested a potato with bone meal but this is what I get:

{
  "block": {
    "base_type": "POTATO",
    "item": "POTATO",
    "location": {
      "x": -241.0,
      "y": 70.0,
      "z": 374.0
    }
  },
  "player": {
    "type": "player",
    "name": "LordProducer008",
    "location": {
      "x": -239.21,
      "y": 70.0,
      "z": 373.01
    },
    "potions": [],
    "currentHealth": 9.4,
    "maxHealth": 20.0
  },
  "tool": {
    "item": "**INK_SACK**",
    "enchantments": []
  },
  "category": "block",
  "gameTime": 119296280,
  "minecraft_server": "SplunkCraftMadScience",
  "world": "SplunkMadScience",
  "action": "break"
}

**Comment by PowerSchill** [comment]
That is a strange issue because I am grabbing the item from the player's main hand. 

``` python
ItemStack instrument = ((BlockBreakEvent) event).getPlayer().getInventory().getItemInMainHand();
```

**Comment by TheProducer835** [comment]
it's the MC code and where you grab it from. there may be no way around it.  if in game you say /give <player> minecraft:bonemeal  it does and the response is Gave <playername> Ink Sack!

**Comment by TheProducer835** [comment]
worth considering
